---
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  EcsCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName:
        Fn::Sub: "${EnvironmentName}-services"
      ClusterSettings:
      - Name: containerInsights
        Value: disabled
      Tags:
      - Key: Name
        Value:
          Fn::Sub: "${EnvironmentName}-ecs"
      - Key: Environment
        Value:
          Ref: EnvironmentName
      - Key: EnvironmentType
        Value:
          Ref: EnvironmentType
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId:
        Ref: VPCId
      GroupDescription: greeter-service fargate service
    Metadata:
      cfn_nag:
        rules_to_suppress:
        - id: F1000
          reason: ignore egress for now
  EcsFargateService:
    Type: AWS::ECS::Service
    Properties:
      Cluster:
        Ref: EcsCluster
      DesiredCount: '1'
      DeploymentConfiguration:
        MinimumHealthyPercent: '100'
        MaximumPercent: '200'
      TaskDefinition:
        Ref: Task
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
          - Ref: SecurityGroup
          Subnets:
            Ref: SubnetIds
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Ref: AWS::StackName
      RetentionInDays: '7'
  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ecs-tasks.amazonaws.com
          Action:
          - sts:AssumeRole
        - Effect: Allow
          Principal:
            Service:
            - ssm.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: fargate_default_policy
        PolicyDocument:
          Statement:
          - Sid: fargatedefaultpolicy
            Action:
            - logs:GetLogEvents
            Resource:
            - Fn::GetAtt:
              - LogGroup
              - Arn
            Effect: Allow
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: ecs-tasks.amazonaws.com
          Action: sts:AssumeRole
        - Effect: Allow
          Principal:
            Service: ssm.amazonaws.com
          Action: sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
  Task:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
      - Name: greeter
        Image:
          Fn::Join:
          - ''
          - - ''
            - greeter
            - ":"
            - latest
        LogConfiguration:
          LogDriver: awslogs
          Options:
            awslogs-group:
              Ref: LogGroup
            awslogs-region:
              Ref: AWS::Region
            awslogs-stream-prefix: greeter
      RequiresCompatibilities:
      - FARGATE
      Cpu: 1024
      Memory: 2048
      NetworkMode: awsvpc
      TaskRoleArn:
        Ref: TaskRole
      ExecutionRoleArn:
        Ref: ExecutionRole
      Tags:
      - Key: Name
        Value: greeterserviceTask
      - Key: Environment
        Value:
          Ref: EnvironmentName
      - Key: EnvironmentType
        Value:
          Ref: EnvironmentType
Outputs:
  CfTemplateUrl:
    Value: "/greeter.compiled.yaml"
  CfTemplateVersion:
    Value: latest
  EcsCluster:
    Value:
      Ref: EcsCluster
    Export:
      Name:
        Fn::Sub: "${EnvironmentName}-ecs-EcsCluster"
  EcsClusterArn:
    Value:
      Fn::GetAtt:
      - EcsCluster
      - Arn
    Export:
      Name:
        Fn::Sub: "${EnvironmentName}-ecs-EcsClusterArn"
  ecsCfTemplateUrl:
    Value: "/ecs-v2.compiled.yaml"
  ecsCfTemplateVersion:
    Value: latest
  SecurityGroup:
    Value:
      Ref: SecurityGroup
    Export:
      Name:
        Fn::Sub: "${EnvironmentName}-greeter-service-SecurityGroup"
  ServiceName:
    Value:
      Fn::GetAtt:
      - EcsFargateService
      - Name
    Export:
      Name:
        Fn::Sub: "${EnvironmentName}-greeter-service-ServiceName"
  EcsTaskArn:
    Value:
      Ref: Task
    Export:
      Name:
        Fn::Sub: "${EnvironmentName}-greeterserviceTask-EcsTaskArn"
  greeterserviceTaskCfTemplateUrl:
    Value: "/ecs-task.compiled.yaml"
  greeterserviceTaskCfTemplateVersion:
    Value: latest
  greeter-serviceCfTemplateUrl:
    Value: "/fargate-v2.compiled.yaml"
  greeter-serviceCfTemplateVersion:
    Value: latest
Parameters:
  VPCId:
    Type: String
    Default: ''
    NoEcho: false
  SubnetIds:
    Type: String
    Default: ''
    NoEcho: false
  GreeterServiceTag:
    Type: String
    Default: ''
    NoEcho: false
  EnvironmentName:
    Type: String
    Default: dev
    NoEcho: false
  EnvironmentType:
    Type: String
    Default: development
    NoEcho: false
    AllowedValues:
    - development
    - production
Description: Greeter Service - (greeter@latest)
