---
task_type: FARGATE
network_mode: awsvpc
cpu: 256
memory: 512
iam_policies:
  fargate_default_policy:
    action:
    - logs:GetLogEvents
    resource:
    - Fn::GetAtt:
      - LogGroup
      - Arn
:platform_version: 1.4.0
:cpu: 1024
:memory: 2048
:task_definition:
  :greeter:
    :repo: repo
    :image: nginx
    :tag_param: GreeterVersion
nested_component: true
component_version: latest
component_name: greeterserviceTask
template_name: ecs-task
template_version: secrets
template_dir: "/Users/aaronwalker/.cfhighlander/components/ecs-task/secrets"
description: ecs-task - greeterserviceTask - latest
